#!/bin/zsh
cat ~/Dev/UD_Marathi/no_release/$1.vislcg.txt.new | python ~/Dev/Apertium/scripts/vislcg3-to-conllu.py > ~/Dev/UD_Marathi/no_release/UD_Marathi.conllu
cat UD_Marathi.conllu | python convert.py | python sort.py | sponge UD_Marathi.conllu
